version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=ITIC_DB
      - POSTGRES_PASSWORD=ITIC
      - POSTGRES_USER=ITIC_user
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_oriol.gonzalez@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: oriol123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
