# Generated by Django 5.1.6 on 2025-02-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='contrasenya',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
