# Generated by Django 5.1.6 on 2025-02-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_usuari_contrasenya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuari',
            old_name='ciutat',
            new_name='telefon',
        ),
    ]
